
```{r}
install.packages("lubridate")
install.packages("stringr")
```


```{r}
library(ggplot2)
library(arules)
library(dplyr)
library(tidyverse)
library(lubridate)
library(stringr)

```

```{r}
#link = https://www.kaggle.com/datasets/deepshah16/song-lyrics-dataset/data 
artist_names <- list.files(path = "FILE PATH", pattern = "\\.csv$", full.names = TRUE)

df_list <- list()

for (file in artist_names) {
  df <- read.csv(file, strip.white=TRUE)
  df <- df[, !names(df) %in% "X"]
  df_list[[length(df_list) + 1]] <- df
}

artist_df <- do.call(rbind, df_list)


#link = https://www.kaggle.com/datasets/arnavvvvv/spotify-music?resource=download
pop_songs <- as.data.frame(Popular_Spotify_Songs)
names(pop_songs)[1] <- "Title"
names(pop_songs)[2] <- "Artist"

```

```{r}
check_overlap <- function(artist1, artist2) {
  any(str_detect(artist1, artist2))
}


pop_songs$Artist <- gsub("Beyonc", "Beyoncé", pop_songs$Artist)
pop_songs$Artist <- gsub("<ef><bf>", "", pop_songs$Artist)

songs <- merge(pop_songs, artist_df, by = "Title", all = FALSE)
songs <- select(songs,c("Title", "Artist.y", "Artist.x", "Date", "bpm", "key", "valence_%", "Lyric", "in_spotify_charts"))

songs <- songs %>% 
  mutate(Date = as.Date(Date)) %>%
  mutate(Year = year(Date), 
         Month = month(Date), 
         Day = day(Date))

songs <- songs[apply(songs[c("Artist.x", "Artist.y")], 1, function(x) check_overlap(x[1], x[2])), ] 


```

```{r}

colnames(songs) <- c("Title","Artist.x", "Artist", "Date","BPM", "Key", "Valence", "Lyrics","Charts", "Year", "Month","Day")
songs <- select(songs,c("Title", "Artist", "Year","Month","Day", "Lyrics", "BPM", "Key", "Valence", "Charts"))
songs <- na.omit(songs)

```

```{r}
write_csv(songs, "songs.csv")
write_csv(pop_songs, "pop_songs.csv")
write_csv(artist_df, "compiled_artist.csv")
```

